events {}
http {
  include mime.types;
  server {
    listen 8080;
    root D:/68535/Sample/blazor-pwa-redirect-validation/NET11/PwaRedirectTest/bin/Release/net11.0/publish/wwwroot;
    location = /index.html { return 301 /; }
    location / { try_files $uri /index.html =404; }
  }
}