events {}
http {
  include mime.types;
  server {
    listen 8090;
    root D:/68535/PwaRedirectTest/bin/Release/net10.0/publish/wwwroot;
    location = /index.html { return 301 /; }
    location / { try_files $uri /index.html =404; }
  }
}